//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationSearchEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public string PhotoId { get; set; }
        public string Title { get; set; }
        public int Farm { get; set; }
        public string Server { get; set; }
        public string Secret { get; set; }
        public int VenueId { get; set; }
    
        public virtual Venue Venue { get; set; }
    }
}
